### ISSUE TITLE
How do I get the latest nuget version?

### ISSUE THREAD

**Issue by wosledon** [juliusfriedman/net7mma_core#37]

**Comment by juliusfriedman** [comment]
How is this an issue and not a discussion?

There is a fee ;) 

More seriously, I will work on adding a new nuget in due course, the project is just not ready for that yet IMHO, if you feed differently please let me know. (Each project should perhaps be its own nuget)

There is a nuget for the old version simply because I didn't make it, someone else contributed it, if you think you can add some pipeline step to the build action then by all means I will review it just as I have other contributions.

**Comment by juliusfriedman** [comment]
See also https://stackoverflow.com/questions/74927029/create-nuget-package-with-github-actions or https://acraven.medium.com/a-nuget-package-workflow-using-github-actions-7da8c6557863, it would push here -> https://www.nuget.org/packages/net7mma/
