### ISSUE TITLE
测试 rtsp server

### ISSUE THREAD

**Issue by chinasoftsky** [juliusfriedman/net7mma_core#6]
RestartFaultedStreams
DisconnectAndRemoveInactiveSessions
RestartFaultedStreams
DisconnectAndRemoveInactiveSessions
RestartFaultedStreams
DisconnectAndRemoveInactiveSessions 

1测试 打印这些日志   无法访问  
2  有没有demo  怎么用客服端访问  访问地址多少 
3  ffmpeg 可以推流吗

**Comment by juliusfriedman** [comment]
The demo would be Mirror or Bandit which are MJPEG streams.

I don't understand what you mean about accessing the client if your getting those errors, it's possible it's just normal logging...

Change the timer for the `Maintainer` if it's too short for your needs.

You can also disable the `Maintainer` if it's getting in the way and do maintenance yourself at the method level. (i.e. in TEARDOWN etc.)

The server as is supported up to 200k + users before I hit that issue.

Make sure your machine is equipped with the memory and cpu and bandwidth it needs to serve the video otherwise this is going be the result using any library.

Let me know if you need further assistance.
